### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by 0xMRTT** [Intel-Student-Ambassadors/welcome#21]
### Name

0xMRTT

### Email Address

0xMRTT@tuta.io

### Additional Context

I want to join this community because i use intel a lot

### What areas you can contribute / interested to work in?

Web Development

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
Hi,

Github actions reported an error with credentials

**Comment by hariketsheth** [comment]
@0xMRTT  The Token had expired. I have renewed it.
Welcome to the Community 💪💕 !!!

**Comment by 0xMRTT** [comment]
Hi 👋

**Comment by hariketsheth** [comment]
Hey
