### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by kcraftcode** [Intel-Student-Ambassadors/welcome#238]
### Name

Ethan Tan

### Email Address

kentaurse0212@gmail.com

### Additional Context

I specialize in blockchain development and website creation for businesses and individuals.
I apply advanced skills to blockchain development, including expertise in smart contract creation, decentralized application (dApp) development, and blockchain architecture design. My experience includes various blockchain platforms such as Ethereum, Hyperledger, and Binance Smart Chain. I also have a deep understanding of cryptographic principles, consensus algorithms, and security best practices in blockchain technology.
I make it a priority to deliver high-quality projects while building genuine friendships and fostering meaningful relationships in both professional and personal spheres. If you are looking for someone who can support you in both business and life, send me a DM.

### What areas you can contribute / interested to work in?

Web Development

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by technyk** [comment]
> Beware, this user appears to be a fake account. They have been asking various orgs (including an org I'm in via Discord) for full access without any real reasoning, and their GitHub appears to be bot driven. Some other examples of access requests with little-to-no reasoning:
> 
> 1. [Invite me your team collective.inviting#2](https://github.com/collective/collective.inviting/issues/2)
> 2. [Please add me to the collective #1868](https://github.com/collective/Collective/issues/1868)
> 3. [I want to join this oganization jenkinsci/multibranch-action-triggers-plugin#30](https://github.com/jenkinsci/multibranch-action-triggers-plugin/issues/30)
> 4. [I want to join your team kimurayu45z/ng-algoliasearch#28](https://github.com/kimurayu45z/ng-algoliasearch/issues/28) 
> 
> Most of their repos are forks / fake re-uploads, e.g.https://github.com/kentaurse/blockchain-tutorial which is a clone of https://github.com/nosequeldeebee/blockchain-tutorial but with the git history re-written to make it seem like they authored it.
